version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: securecorp

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  securecorp-api:
    build: .

    depends_on:
      - postgres

    ports:
      - "3000:3000"

    env_file:
      - .env

volumes:
  postgres_data:
